image: atlassian/default-image:3

pipelines:
  pull-requests:
    "**":
      - step:
          name: Lint code
          script:
            - apt-get update
            - apt-get -y install lua5.1
            - apt-get -y install luarocks
            - luarocks install luacheck
            - luacheck .
  branches:
    master:
      - step:
          name: Lint code
          script:
            - apt-get update
            - apt-get -y install lua5.1
            - apt-get -y install luarocks
            - luarocks install luacheck
            - luacheck .